apiVersion: apps/v1
kind: Deployment
metadata:
  name: gift-app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: ENV
              value: "DEV"
            - name: APP_VERSION
              value: dev-32