apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

images:
  - name: srshin80/gift-app
    newName: srshin80/gift-app
    newTag: "17"   # Jenkins가 'kustomize edit set image'로 덮어씀
