apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - path: deployment-patch.yaml

images:
  - name: srshin80/gift-app
    newTag: "fixed-version"
