apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

images:
  - name: srshin80/gift-app
    # prod는 Jenkins 'prod-rollout/rollback' 단계에서 set image로 덮어씀