apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-app-prod
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/srshin80/repo-config.git
    targetRevision: main
    path: services/repo-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy: {}
